---
# This role provides the minimum permissions to run apache
# "Spark over Kubernetes" by providing the caller service account in
# another namespace the rights to create|list|watch|delete pods in another.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-pod-scheduler
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - nonroot
  verbs:
    - use
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods
    - persistentvolumeclaims
    - services
  verbs:
    - list
    - watch
    - create
    - delete
