---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spark-pod-scheduler
subjects:
  - kind: ServiceAccount
    name: jupyter-notebooks
    namespace: jupyter-notebooks
roleRef:
  kind: ClusterRole
  name: spark-pod-scheduler
  apiGroup: rbac.authorization.k8s.io