{{- $root := . -}}
{{- range .Values.jupyterNotebooks.users }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-pyspark-jupyter-notebook
spec:
  type: LoadBalancer
  ports:
  - name: notebook-gui
    port: 8888
    targetPort: 8888
  - name: spark-driver-gui
    port: 4040
    targetPort: 4040
  - name: spark-driver-port
    port: 4041
    targetPort: 4041
  selector:
    app: {{ .name }}-pyspark-jupyter-notebook
{{- end }}