apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.jupyterNotebooks.namespace }}-deployment
  namespace: {{ .Values.jupyterNotebooks.namespace }}
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - nonroot
  verbs:
    - use
