{{- range .Values.partitions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}-pod-scheduler
  namespace: {{ .name | quote }}
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - nonroot
  verbs:
    - use
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods
    - persistentvolumeclaims
    - services
  verbs:
    - list
    - watch
    - create
    - delete
    - deletecollection
{{- end }}