kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount }}-scheduler
  namespace: {{ .Values.partition | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount | quote }}
    namespace: {{ .Values.namespace | quote }}
roleRef:
  kind: ClusterRole
  name: spark-on-k8s-scheduler
  apiGroup: rbac.authorization.k8s.io
