{{- $root := . -}}
{{- range .Values.notebooks }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-notebook
  namespace: {{ $root.Values.namespace | quote }}
  labels:
    app: {{ .name }}-notebook
spec:
  selector:
    matchLabels:
      app: {{ .name }}-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .name }}-notebook
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccount: {{ $root.Values.serviceAccount | quote }}
      serviceAccountName: {{ $root.Values.serviceAccount | quote }}
      containers:
        - name: {{ .name }}-notebook
          image: {{ $root.Values.image.repository | quote }}
          imagePullPolicy: {{ $root.Values.image.pullPolicy | quote }}
          resources:
            limits:
              memory: 5Gi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: workdir
            mountPath: /home/jovyan/work
      volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: {{ .name }}-notebook-workfiles
{{- end }}