{{- $root := . -}}
{{- range .Values.notebooks }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-notebook-workfiles
  namespace: {{ $root.Values.namespace | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}