kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.namespace | quote }}
  namespace: {{ .Values.namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount | quote }}
    namespace: {{ .Values.namespace | quote }}
roleRef:
  kind: Role
  name: nonroot
  apiGroup: rbac.authorization.k8s.io
