apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nonroot
  namespace: {{ .Values.namespace | quote }}
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - nonroot
  verbs:
    - use
