apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spark-on-k8s-scheduler
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - nonroot
  verbs:
    - use
- apiGroups:
    - ""
  resources:
    - configmaps
    - pods
    - persistentvolumeclaims
    - services
  verbs:
    - list
    - get
    - watch
    - create
    - delete
    - deletecollection
