---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyspark-jupyter-notebook-work-files
  namespace: jupyter-notebooks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyspark-jupyter-notebook
  namespace: jupyter-notebooks
  labels:
    app: pyspark-jupyter-notebook
spec:
  selector:
    matchLabels:
      app: pyspark-jupyter-notebook
  replicas: 1
  template:
    metadata:
      labels:
        app: pyspark-jupyter-notebook
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: "OnRootMismatch"
      serviceAccount: jupyter-notebooks
      serviceAccountName: jupyter-notebooks
      containers:
        - name: pyspark-jupyter-notebook
          image: quay.io/rh_ee_cengleby/pyspark-notebook:0.7
          imagePullPolicy: Always
          resources:
            limits:
              memory: 5Gi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8888
          volumeMounts:
          - name: workdir
            mountPath: /home/jovyan/work
      volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: pyspark-jupyter-notebook-work-files
---
apiVersion: v1
kind: Service
metadata:
  name: pyspark-jupyter-notebook
spec:
  type: LoadBalancer
  ports:
  - name: notebook-port
    port: 8888
    targetPort: 8888
  - name: spark-driver-port
    port: 4040
    targetPort: 4040
  - name: spark-driver-port-2
    port: 4041
    targetPort: 4041
  selector:
    app: pyspark-jupyter-notebook
