apiVersion: v1
kind: Pod
spec:
  containers:
    - resources:
        limits:
          cpu: '1'
          memory: '2Gi'
        requests:
          cpu: '1'
          memory: '1Gi'
      args:
      env:
        - name: SPARK_EXECUTOR_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name